/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/_admin/subscriptions'
import { Route as AdminRevenueRouteImport } from './routes/_admin/revenue'
import { Route as AdminPlansRouteImport } from './routes/_admin/plans'
import { Route as AdminPaymentsRouteImport } from './routes/_admin/payments'
import { Route as AdminOrganizationsRouteImport } from './routes/_admin/organizations'
import { Route as AdminLeadsRouteImport } from './routes/_admin/leads'
import { Route as AdminInboxRouteImport } from './routes/_admin/inbox'
import { Route as AdminEmailConfigRouteImport } from './routes/_admin/email-config'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAutomationsRouteImport } from './routes/_admin/automations'
import { Route as AdminAiUsageRouteImport } from './routes/_admin/ai-usage'
import { Route as AdminAccessRequestsRouteImport } from './routes/_admin/access-requests'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users.index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/_admin/payments.index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/_admin/organizations.index'
import { Route as AdminLeadsIndexRouteImport } from './routes/_admin/leads.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users.$userId'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/_admin/payments.$paymentId'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/_admin/organizations.$orgId'
import { Route as AdminLeadsLeadIdRouteImport } from './routes/_admin/leads.$leadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailConfigRoute = AdminEmailConfigRouteImport.update({
  id: '/email-config',
  path: '/email-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationsRoute = AdminAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRequestsRoute = AdminAccessRequestsRouteImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/$paymentId',
  path: '/$paymentId',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AdminLeadsLeadIdRoute = AdminLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AdminLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access-requests': typeof AdminAccessRequestsRoute
  '/ai-usage': typeof AdminAiUsageRoute
  '/automations': typeof AdminAutomationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/email-config': typeof AdminEmailConfigRoute
  '/inbox': typeof AdminInboxRoute
  '/leads': typeof AdminLeadsRouteWithChildren
  '/organizations': typeof AdminOrganizationsRouteWithChildren
  '/payments': typeof AdminPaymentsRouteWithChildren
  '/plans': typeof AdminPlansRoute
  '/revenue': typeof AdminRevenueRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/users': typeof AdminUsersRouteWithChildren
  '/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/leads/': typeof AdminLeadsIndexRoute
  '/organizations/': typeof AdminOrganizationsIndexRoute
  '/payments/': typeof AdminPaymentsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access-requests': typeof AdminAccessRequestsRoute
  '/ai-usage': typeof AdminAiUsageRoute
  '/automations': typeof AdminAutomationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/email-config': typeof AdminEmailConfigRoute
  '/inbox': typeof AdminInboxRoute
  '/plans': typeof AdminPlansRoute
  '/revenue': typeof AdminRevenueRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/leads': typeof AdminLeadsIndexRoute
  '/organizations': typeof AdminOrganizationsIndexRoute
  '/payments': typeof AdminPaymentsIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/access-requests': typeof AdminAccessRequestsRoute
  '/_admin/ai-usage': typeof AdminAiUsageRoute
  '/_admin/automations': typeof AdminAutomationsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/email-config': typeof AdminEmailConfigRoute
  '/_admin/inbox': typeof AdminInboxRoute
  '/_admin/leads': typeof AdminLeadsRouteWithChildren
  '/_admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/_admin/payments': typeof AdminPaymentsRouteWithChildren
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/revenue': typeof AdminRevenueRoute
  '/_admin/subscriptions': typeof AdminSubscriptionsRoute
  '/_admin/users': typeof AdminUsersRouteWithChildren
  '/_admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/_admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/_admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_admin/leads/': typeof AdminLeadsIndexRoute
  '/_admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/_admin/payments/': typeof AdminPaymentsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access-requests'
    | '/ai-usage'
    | '/automations'
    | '/dashboard'
    | '/email-config'
    | '/inbox'
    | '/leads'
    | '/organizations'
    | '/payments'
    | '/plans'
    | '/revenue'
    | '/subscriptions'
    | '/users'
    | '/leads/$leadId'
    | '/organizations/$orgId'
    | '/payments/$paymentId'
    | '/users/$userId'
    | '/leads/'
    | '/organizations/'
    | '/payments/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access-requests'
    | '/ai-usage'
    | '/automations'
    | '/dashboard'
    | '/email-config'
    | '/inbox'
    | '/plans'
    | '/revenue'
    | '/subscriptions'
    | '/leads/$leadId'
    | '/organizations/$orgId'
    | '/payments/$paymentId'
    | '/users/$userId'
    | '/leads'
    | '/organizations'
    | '/payments'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/access-requests'
    | '/_admin/ai-usage'
    | '/_admin/automations'
    | '/_admin/dashboard'
    | '/_admin/email-config'
    | '/_admin/inbox'
    | '/_admin/leads'
    | '/_admin/organizations'
    | '/_admin/payments'
    | '/_admin/plans'
    | '/_admin/revenue'
    | '/_admin/subscriptions'
    | '/_admin/users'
    | '/_admin/leads/$leadId'
    | '/_admin/organizations/$orgId'
    | '/_admin/payments/$paymentId'
    | '/_admin/users/$userId'
    | '/_admin/leads/'
    | '/_admin/organizations/'
    | '/_admin/payments/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subscriptions': {
      id: '/_admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/revenue': {
      id: '/_admin/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations': {
      id: '/_admin/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/leads': {
      id: '/_admin/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inbox': {
      id: '/_admin/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/email-config': {
      id: '/_admin/email-config'
      path: '/email-config'
      fullPath: '/email-config'
      preLoaderRoute: typeof AdminEmailConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/automations': {
      id: '/_admin/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AdminAutomationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-usage': {
      id: '/_admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/access-requests': {
      id: '/_admin/access-requests'
      path: '/access-requests'
      fullPath: '/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/_admin/payments/': {
      id: '/_admin/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/_admin/organizations/': {
      id: '/_admin/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    '/_admin/leads/': {
      id: '/_admin/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/_admin/payments/$paymentId': {
      id: '/_admin/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/_admin/organizations/$orgId': {
      id: '/_admin/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    '/_admin/leads/$leadId': {
      id: '/_admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AdminLeadsLeadIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
  }
}

interface AdminLeadsRouteChildren {
  AdminLeadsLeadIdRoute: typeof AdminLeadsLeadIdRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsLeadIdRoute: AdminLeadsLeadIdRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminPaymentsRouteChildren {
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminAutomationsRoute: typeof AdminAutomationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailConfigRoute: typeof AdminEmailConfigRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminAutomationsRoute: AdminAutomationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailConfigRoute: AdminEmailConfigRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminPlansRoute: AdminPlansRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
